# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    '''
    class that hosts the code responsible for setup and translation of GUI widgets
    '''
    def setupUi(self, MainWindow) -> None:
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 450)
        MainWindow.setMinimumSize(QtCore.QSize(300, 450))
        MainWindow.setMaximumSize(QtCore.QSize(300, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_positive_cookie = QtWidgets.QPushButton(self.centralwidget)
        self.button_positive_cookie.setGeometry(QtCore.QRect(230, 50, 31, 23))
        self.button_positive_cookie.setObjectName("button_positive_cookie")
        self.button_negative_cookie = QtWidgets.QPushButton(self.centralwidget)
        self.button_negative_cookie.setGeometry(QtCore.QRect(170, 50, 31, 23))
        self.button_negative_cookie.setObjectName("button_negative_cookie")
        self.label_cookie_amount = QtWidgets.QLabel(self.centralwidget)
        self.label_cookie_amount.setGeometry(QtCore.QRect(210, 50, 16, 21))
        self.label_cookie_amount.setObjectName("label_cookie_amount")
        self.button_positive_sandwich = QtWidgets.QPushButton(self.centralwidget)
        self.button_positive_sandwich.setGeometry(QtCore.QRect(230, 100, 31, 23))
        self.button_positive_sandwich.setObjectName("button_positive_sandwich")
        self.label_sandwich_amount = QtWidgets.QLabel(self.centralwidget)
        self.label_sandwich_amount.setGeometry(QtCore.QRect(210, 100, 16, 21))
        self.label_sandwich_amount.setObjectName("label_sandwich_amount")
        self.button_negative_sandwich = QtWidgets.QPushButton(self.centralwidget)
        self.button_negative_sandwich.setGeometry(QtCore.QRect(170, 100, 31, 23))
        self.button_negative_sandwich.setObjectName("button_negative_sandwich")
        self.button_positive_water = QtWidgets.QPushButton(self.centralwidget)
        self.button_positive_water.setGeometry(QtCore.QRect(230, 150, 31, 23))
        self.button_positive_water.setObjectName("button_positive_water")
        self.label_water_amount = QtWidgets.QLabel(self.centralwidget)
        self.label_water_amount.setGeometry(QtCore.QRect(210, 150, 16, 21))
        self.label_water_amount.setObjectName("label_water_amount")
        self.button_negative_water = QtWidgets.QPushButton(self.centralwidget)
        self.button_negative_water.setGeometry(QtCore.QRect(170, 150, 31, 23))
        self.button_negative_water.setObjectName("button_negative_water")
        self.label_amount = QtWidgets.QLabel(self.centralwidget)
        self.label_amount.setGeometry(QtCore.QRect(190, 20, 47, 13))
        self.label_amount.setObjectName("label_amount")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(30, 210, 211, 141))
        self.label_output.setObjectName("label_output")
        self.label_cookie = QtWidgets.QLabel(self.centralwidget)
        self.label_cookie.setGeometry(QtCore.QRect(30, 50, 111, 21))
        self.label_cookie.setObjectName("label_cookie")
        self.label_sandwich = QtWidgets.QLabel(self.centralwidget)
        self.label_sandwich.setGeometry(QtCore.QRect(30, 100, 111, 21))
        self.label_sandwich.setObjectName("label_sandwich")
        self.label_water = QtWidgets.QLabel(self.centralwidget)
        self.label_water.setGeometry(QtCore.QRect(30, 150, 111, 21))
        self.label_water.setObjectName("label_water")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(40, 380, 75, 23))
        self.button_clear.setObjectName("button_clear")
        self.button_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.button_calculate.setGeometry(QtCore.QRect(180, 380, 75, 23))
        self.button_calculate.setObjectName("button_calculate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow) -> None:
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Food Menu"))
        self.button_positive_cookie.setText(_translate("MainWindow", "+"))
        self.button_negative_cookie.setText(_translate("MainWindow", "-"))
        self.label_cookie_amount.setText(_translate("MainWindow", "0"))
        self.button_positive_sandwich.setText(_translate("MainWindow", "+"))
        self.label_sandwich_amount.setText(_translate("MainWindow", "0"))
        self.button_negative_sandwich.setText(_translate("MainWindow", "-"))
        self.button_positive_water.setText(_translate("MainWindow", "+"))
        self.label_water_amount.setText(_translate("MainWindow", "0"))
        self.button_negative_water.setText(_translate("MainWindow", "-"))
        self.label_amount.setText(_translate("MainWindow", "Amount"))
        self.label_output.setText(_translate("MainWindow", "Please Enter Your Order"))
        self.label_cookie.setText(_translate("MainWindow", "Cookie  --  $  1.50"))
        self.label_sandwich.setText(_translate("MainWindow", "Sandwich  --  $  4.00"))
        self.label_water.setText(_translate("MainWindow", "Water  --  $  1.00"))
        self.button_clear.setText(_translate("MainWindow", "CLEAR"))
        self.button_calculate.setText(_translate("MainWindow", "CALCULATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
